### ISSUE TITLE
Sample build failed

### ISSUE THREAD

**Issue by retsohuang** [kitecomp/kitekit#1]
Missing required module `KiteKitPrivate`

**Comment by naeemshaikh90** [comment]
https://github.com/vsouza/awesome-ios/pull/1547

**Comment by CharlesSieg** [comment]
I have same issue building sample app: Missing required module KiteKitPrivate

**Comment by shyswork** [comment]
Can confirm the same issue.

**Comment by kitecomp** [comment]
Hey all, I updated the repo to resolve this issue. One thing I found out though: "Whole Module Optimization" is needed to compile the app – even in debug mode – or Swift will fail with a "module merge" error. I'm still looking into this, but if you have any tips on how to resolve this please let me know!

**Comment by kitecomp** [comment]
Also, I turned on notifications for this repo so I'll see these messages quicker next time. ;)

**Comment by kitecomp** [comment]
@retsohuang Are you still seeing this issue with the latest v1.0.1 release of KiteKit?

**Comment by retsohuang** [comment]
It works now 👍
