### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by xinsight** [kitecomp/kitekit#4]
Could you add a license for KiteKit?

Also, as you are using other projects in KiteKit, you should probably include those licenses (where relevant) as well.

e.g. PocketSVG

**Comment by kitecomp** [comment]
Thanks for the note – I'll add these to the repo shortly. Yes PocketSVG, FBKVOController, and maybe one or two others. I'll push an update to the repo.

**Comment by kitecomp** [comment]
Added a license file.
