### ISSUE TITLE
Listen events from kite documents

### ISSUE THREAD

**Issue by ittna** [kitecomp/kitekit#7]
Is it possible to listen events from kite documents? I didn't find any example of that and couldn't figure out from headers if that is possible or not.

**Comment by kitecomp** [comment]
Hey, do you mean like listening for notifications posted from Kite events defined in the Action inspector? Like these:
![notificaiton](https://cloud.githubusercontent.com/assets/25691244/26122267/e4e7470c-3a44-11e7-99c0-e019466cf7cf.png)

**Comment by ittna** [comment]
I guess so if those can be listened in swift through NotificationCenter.
