### ISSUE TITLE
Update Module

### ISSUE THREAD

**Issue by HellowithShivamAgrawal** [kitecomp/kitekit#8]
Error: Module compiled with Swift 3.1 cannot be imported in Swift 3.2.3: /Users/xyz/Downloads/kitekit-master/iOSKiteKitExample

I am unable to run this project. Please Help! 
Or Since the project haven't been updated since so long, Is KiteApp no longer getting update?
Also I am getting error on Device- iOS KiteKitExample.. Screenshot of that is also attached for reference.
![screen shot 2017-12-28 at 11 44 04 am](https://user-images.githubusercontent.com/26916789/34401951-8e0fd200-ebc4-11e7-83cb-c67ffaec9122.png)

![screen shot 2017-12-28 at 11 43 04 am](https://user-images.githubusercontent.com/26916789/34401918-50a415fc-ebc4-11e7-9f8b-31497ae1e34e.png)

**Comment by jrhodes** [comment]
Just updated to the latest Swift 4.2.
