### ISSUE TITLE
Module compiled with Swift 3.1 cannot be imported by the Swift 4.2.1 compiler:

### ISSUE THREAD

**Issue by colinfry** [kitecomp/kitekit#9]
Please recompile framework for Swift 4.2.1 or add cocoapods support. Thanks

**Comment by gooswa** [comment]
I second this. At this point everything should at least be 4.x

Or truly release the source for KiteKit to allow for us to compile for any project.

**Comment by jrhodes** [comment]
Thanks for the reminder – just updated to Swift 4.2!
